
[env]
TERM = "xterm-256color"

[window]
#decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 10
y = 10

[font]
size = 16.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Medium Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Medium"

[general]
live_config_reload = true
